### ISSUE TITLE
Files exported from SLX studio have missing frames and incomplete shadows 

### ISSUE THREAD

**Issue by Sam152** [goto-bus-stop/genie-slp#18]
Here is an example that was imported into SLX studio from AOE2:DE and exported as an SLP file:

![479](https://user-images.githubusercontent.com/820219/163178788-abd19068-1f22-4df9-baac-e84c2adabfc6.png)

The shadows and some of the unit outline doesn't seem to render quite right.

There also seems to be about 10% of the frames that don't render and just turn into empty 128 byte PNG files. SLX studio seems to show all the frames and doesn't have a problem with the shadows, so I'm wondering if I've either used the wrong export options or this library has a bug related to dealing with the assets from DE specifically.

Attached is the reference SLP file (renamed to .zip):

[u_arc_crossbowman_attackA_x2.zip](https://github.com/genie-js/genie-slp/files/8481383/u_arc_crossbowman_attackA_x2.zip)

**Comment by goto-bus-stop** [comment]
most of the modules in this org were made for AoC first, and some of them work with HD, but IIRC none were updated since DE came out.

**Comment by Sam152** [comment]
For anyone reading along, the CLI tool, along with the attached SLP file is a great way to reproduce this issue: https://github.com/genie-js/slp-render

**Comment by Sam152** [comment]
I ended up implementing an SMX renderer to solve this: https://github.com/Sam152/genie-smx
